server:
  port: 8081
  servlet:
    context-path: /business

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    platform: mysql
    url: jdbc:mysql://60.205.190.198:3306/shiny_business?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: weidb
    password: 1234%6
    # 初始连接数
    initialSize: 5
    # 最小连接池数量
    minIdle: 10
    # 最大连接池数量
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    # 配置一个连接在池中最大生存的时间，单位是毫秒
    maxEvictableIdleTimeMillis: 900000
    # 配置检测连接是否有效
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    filters: stat, wall, log4j
    logSlowSql: true

dubbo:
  application:
    name: business-provider
  registry:
    protocol: multicast
    address: 234.10.10.10:2181
  protocol:
    name: dubbo
    port: 20881
#  monitor:
#    protocol: registry


# 日志
project:
  log:
    app:
      name: shiny-service-business
      level: INFO
    path: /soft/apps/logs/business
    sql:
      level: DEBUG
