server:
  port: 8090
  servlet:
    context-path: /manager

dubbo:
  application:
    name: manager-consumer
  registry:
    address: zookeeper://60.205.190.198:2181
    check: false
  monitor:
    protocol: registry
  consumer:
    check: false

# 日志
project:
  log:
    app:
      name: shiny-web-manager
      level: INFO
    path: /soft/apps/logs/manager
    sql:
      level: DEBUG

oss:
  endpoint: endpoint
  keyid: id
  keysecret: keysecret
  filehost: filehost
  bucketname: bucketname